# Generated by Django 2.2.6 on 2019-10-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(editable=False)),
                ('user_name', models.CharField(max_length=255)),
                ('btc_balance', models.IntegerField()),
                ('eth_balance', models.IntegerField()),
            ],
        ),
    ]
